### ISSUE TITLE
toolbar不想让键盘顶上去怎么弄，现在是整体全部上移了。

### ISSUE THREAD

**Issue by RuoYuHoney** [yoyoyaobin/PreventKeyboardBlockUtil#2]

**Comment by RuoYuHoney** [comment]
而且，当前页面有多个edittext的话，比如从上到下依次是et1,et2,et3,et4,这时我设置的view一般就是et4下方的那个view，但是当我点击et1的时候还是会被顶上去。如果et1本身即使键盘弹起也不会被遮挡，就不必再上移了

**Comment by WangkeqiangS** [comment]
请问这个问题怎么解决呢？
