### ISSUE TITLE
修改了一下，自己设置rootView

### ISSUE THREAD

**Issue by RuoYuHoney** [yoyoyaobin/PreventKeyboardBlockUtil#3]
public PreventKeyboardBlockUtil setRootView(ViewGroup rootView) {
        this.rootView = rootView;
        return preventKeyboardBlockUtil;
    }

    PreventKeyboardBlockUtil.getInstance(activity).setBtnView(view).setRootView(rootView).register()

**Comment by RuoYuHoney** [comment]
但是这样一来，虽然toolbar不会被顶上去，但底部的布局上移会遮住toolbar。。。。我再看看。。

**Comment by yoyoyaobin** [comment]
> 但是这样一来，虽然工具栏不会被顶上去，但底部的布局上移会遮住工具栏....我再看看..

嗯是的，一开始我就是把需要移动的view定义出来接收，后来想想还是算了，因为很少会有移动了部分布局后界面还能美观的。。
